### ISSUE TITLE
facing issue in site name 

### ISSUE THREAD

**Issue by GargSaab** [grnet/maas2netbox#24]
what would be the site name in env.list file? we had tried netbox site name but it is giving the following error.

pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'site': ['Select a valid choice. Lab45-5g-edge is not one of the available choices.']}

**Comment by skatsaounis** [comment]
Hi @GargSaab! This tool here is working per NetBox site. Being more specific, it can enrich NetBox device information from information discovered by MaaS but one NetBox site at the time.

The `SITE` applies a filter to NetBox resources. So if I want to work with all devices of e.g. `Lab45` site, I have to set `SITE=Lab45`. The tool will filter out devices of all the other sites and will use only those that have their site set to `Lab45` in NetBox.

**Comment by GargSaab** [comment]
Hi @skatsaounis, thanks for the response. 
I have only 1 site defined in netbox  and used the correct name in env.list file but still it is give select a valid choice. I am sharing screenshots pl have a look at it.
<img width="1440" alt="Screenshot 2023-01-18 at 9 57 34 AM (1)" src="https://user-images.githubusercontent.com/72223984/213089920-21a325c4-8b67-4fcb-8a1f-db6f4212729a.png">
<img width="1152" alt="Screenshot 2023-01-18 at 10 04 20 AM (1)" src="https://user-images.githubusercontent.com/72223984/213089937-45e606b8-6616-4ce1-8321-f52eb18a7ba2.png">
<img width="1440" alt="Screenshot 2023-01-18 at 10 06 13 AM (1)" src="https://user-images.githubusercontent.com/72223984/213089939-31ad299d-1f24-402e-941b-3e7a965d9be9.png">
